site_name: jhc.design
nav:
  - Home: index.md
  - SportShoes: beva.md
  - FormalShoes: formal.md
  - A. Von Humboldt: avh.md
  - Colgado Stool: colgadoStool.md
  - Floating Sink: floatingSink.md
  - Other Prjects:
  - Bunky Website: bunkywebsite.md
  - Offroad Solar Energy: neoGaia.md
  - Office Furniture: atu.md
  - BunkyWebsite: bunkywebsite.md
  - Random sketching: sketchfw.md

theme: material
