site_name: jhc.design
nav:
  - Home: index.md
  - Sport Shoes: beva.md
  - Formal Shoes: formal.md
  - A. Von Humboldt: avh.md
  - Climb Shoe Concept: xnewbalance.md
  - Colgado Stool: colgadoStool.md
  - Floating Sink: floatingSink.md


theme:
  name: material
  font: Ubuntu
  palette:
    primary: white
    accent: green
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jorgehcorrea/
    - icon: fontawesome/brands/behance
      link: https://www.behance.net/jorgecorrea9
  homepage: https://www.jhc.design

plugins:
    - redirects:
        redirect_maps:
            'index.md': 'https://jorgehcorrea.github.io/'
