site_name: jhc.design
nav:
  - Home: index.md
  - SportShoes: beva.md
  - FormalShoes: formal.md
  - A. Von Humboldt: avh.md
  - Bunky Website: bunkywebsite.md


theme: material

extra:
  homepage: https://www.jhc.design

plugins:
    - redirects:
        redirect_maps:
            'index.md': 'https://jorgehcorrea.github.io/'
