site_name: jhc.design
nav:
  - Home: index.md
  - SportShoes: beva.md
  - FormalShoes: formal.md
  - A. Von Humboldt: avh.md
  - Random Concepts: sketchfw.md
  - Bunky website:  bunkywebsite.md
theme: material
  palette:
    primary: white
    accent: light green

extra:
  homepage: https://www.jhc.design

plugins:
    - redirects:
        redirect_maps:
            'index.md': 'https://jorgehcorrea.github.io/'
